# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "Say": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://DropD.github.io/tryout_nbdev/"

git_url = "https://github.com/DropD/tryout_nbdev/tree/default/"

def custom_doc_links(name): return None
